### ISSUE TITLE
Lack of source chain in `assetlist.json` for IBC and L2 assets.

### ISSUE THREAD

**Issue by y-pakorn** [initia-labs/initia-registry#106]
In minitia's `assetlist.json`, there's no way to map between IBC and L2 assets to their respective source chain asset except for fuzzy searching all assets in `denom_units` which is considered counterintuitive and not optimized.

For example, in `testnets/init_ai/assetlist.json` there is TUC token, a native token of Tucana minitia, in this case, the real denom would be `utuc`, but there's no way to know that except I open the `assetlist.json` of Tucana and find that manually.
https://github.com/initia-labs/initia-registry/blob/c510fb1b0825e67e553e9d4801b4657618e10f69/testnets/init_ai/assetlist.json#L118-L123

Please consider adding some information regarding the source chain and source assets, a good example here would be Pulsar's IBC registry.
https://github.com/PulsarDefi/IBC-Token-Data-Cosmos/blob/647ec95d52f67c71e3681cc756bc2d8446fd00e9/ibc_data.json#L5-10

**Comment by simcheolhwan** [comment]
This will be handled later in the format as the link below:

https://github.com/cosmos/chain-registry/blob/master/osmosis/assetlist.json#L101-L130

**Comment by Byte3622** [comment]
Handled yet?

**Comment by monsterkan** [comment]
go go go

**Comment by simcheolhwan** [comment]
#169
