### ISSUE TITLE
lunch app

### ISSUE THREAD

**Issue by Eme1983** [initia-labs/initia-registry#129]
what is the difference between iniatia site and the lunch app? both of them looks alike (like copy cat)

**Comment by MOGonly1** [comment]
This gives easier accesibility to the testnet than connecting your wallet or rather if you don't have a pc. I actually love the idea behind the lunch app.

**Comment by Vritra4** [comment]
initia is Layer-1 chain and lunch is Layer-2 which is one of interwoven rollups
