### ISSUE TITLE
No build output for v0.1.4 on NPM

### ISSUE THREAD

**Issue by siddharthborderwala** [initia-labs/initia-registry#43]
Hi folks, the build output for `v0.1.4` is missing from the package installed via NPM. Please check here - https://www.npmjs.com/package/@initia/initia-registry?activeTab=code

The build outputs for `v0.1.1` and `v0.1.2` have the `main` and `esm` folders. But v0.1.4 is missing those.

Could you please make a `v0.1.5` patch release fixing the above issue?

Thanks a lot!

**Comment by Vritra4** [comment]
sorry for the late response. use v0.1.10 please :)
